---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: os
# description will be included in the image's metadata
description: This is my personal OS image.

# upstream Fedora 45 beta; switch back to ghcr.io/ublue-os/silverblue-main once it ships a 45 tag
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 45

modules:
  - type: rpm-ostree
    install:
      - NetworkManager-openconnect-gnome
      - NetworkManager-openvpn-gnome
      - Thunar
      - blueman
      - bolt
      - dunst
      - foot
      - fprintd-pam
      - gnome-keyring-pam
      - gvfs
      - gvfs-smb
      - grim
      - imv
      - kanshi
      - lxqt-policykit
      - mesa-dri-drivers
      - mesa-vulkan-drivers
      - micro
      - network-manager-applet
      - pam_oo7
      - pavucontrol
      - perl
      - pinentry-gnome3
      - playerctl
      - plymouth-system-theme
      - polkit
      - pulseaudio-utils
      - sddm
      - sddm-wayland-sway
      - slurp
      - sshuttle
      - sway
      - sway-config-fedora
      - swaybg
      - swayidle
      - swaylock
      - system-config-printer
      - thunar-archive-plugin
      - tmux
      - tmux-powerline
      - tuned
      - tuned-ppd
      - tuned-switcher
      - vim-enhanced
      - vim-powerline
      - waybar
      - wev
      - wl-clipboard
      - wlr-randr
      - wlsunset
      - xarchiver
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
      - xen
      - xen-libs
      - xen-runtime
      - xorg-x11-server-Xwayland
      - zsh
      - btop
      - golang
      - piper
      - logiops
      - wf-recorder
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

