---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: os
# description will be included in the image's metadata
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - NetworkManager-l2tp-gnome
      - NetworkManager-libreswan-gnome
      - NetworkManager-openconnect-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-pptp-gnome
      - NetworkManager-sstp-gnome
      - NetworkManager-vpnc-gnome
      - Thunar
      - blueman
      - bolt
      - cockpit-machines
      - cockpit-networkmanager
      - cockpit-ostree
      - cockpit-podman
      - cockpit-storaged
      - cockpit-system
      - cockpit-ws
      - dunst
      - foot
      - fprintd-pam
      - gnome-keyring-pam
      - gnome-themes-extra
      - grim
      - imv
      - kanshi
      - lxqt-policykit
      - mesa-dri-drivers
      - mesa-vulkan-drivers
      - micro
      - network-manager-applet
      - pavucontrol
      - perl
      - pinentry-gnome3
      - playerctl
      - plymouth-system-theme
      - polkit
      - pulseaudio-utils
      - sddm
      - sddm-wayland-sway
      - slurp
      - sshuttle
      - starship
      - sway
      - sway-config-fedora
      - swaybg
      - swayidle
      - swaylock
      - system-config-printer
      - thunar-archive-plugin
      - tmux
      - tmux-powerline
      - tuned
      - tuned-switcher
      - vim-enhanced
      - vim-powerline
      - waybar
      - wev
      - wl-clipboard
      - wlr-randr
      - wlsunset
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
      - xorg-x11-server-Xwayland
      - zsh
      - qutebrowser
      - btop


  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

